### ISSUE TITLE
【選択日の予約表示画面】予約取消処理

### ISSUE THREAD

**Issue by tamura-shunsuke** [ixui/meeting-room-booking#14]
## 機能概要
「取消」ボタン押下時に選択された予約のIDを取得し、削除する
削除後は、再度この画面を表示する

**Comment by ta2yak** [comment]
> 削除後は、再度この画面を表示する
これはどういうこと？？
データないのにがんばって表示する感じ？？

**Comment by tamura-shunsuke** [comment]
その日付の予約がすべて表示されているので、削除されたことが分かるようにもう一度表示しようと思いました。
他に予約がない場合はテーブルのラベル？だけの表示になってしまいます…

**Comment by ta2yak** [comment]
その日の予定画面なのね
なるほど

予約がない場合の表示は専用の表示を用意することでぐっとクオリティがあがるよ
今後、時間があるようだったらそういう機能も足せるといいね


[参考](https://jp.pinterest.com/alessia87/empty-data/)

**Comment by tamura-shunsuke** [comment]
参考サイトありがとうございます。
週末時間があったら作ります。

**Comment by tamura-shunsuke** [comment]
予約取消機能実装しました。
developで作業してしまっていたので、これ以降issue毎にブランチをきって作業します。
