### ISSUE TITLE
【予約修正画面】予約取消処理

### ISSUE THREAD

**Issue by tamura-shunsuke** [ixui/meeting-room-booking#18]
### 機能概要
「取消」ボタン押下時に表示されている予約の予約IDを取得し、予約を削除する
### 仕様概要
・削除できるのは予約者本人のみ

**Comment by ta2yak** [comment]
だれでも削除可能？

issueに簡単な仕様を書いておくといいかもしれないね

**Comment by tamura-shunsuke** [comment]
issue修正しました。

はい、そのようにします。
