### ISSUE TITLE
【ログイン】 ログイン処理

### ISSUE THREAD

**Issue by ta2yak** [ixui/meeting-room-booking#7]
#### 機能概要
「ログイン」ボタン押下時に入力されたIDとパスワードを使用しログインを行う
ログイン後のユーザ情報はセッションに保持する

#### 気を付けること
- パスワードは入力時に見えないようにすること(type="password"を使う)
- パスワードは非可逆変換されて登録されているので、ログイン時にも同じ変換を行いチェックすること

**Comment by ta2yak** [comment]
issueにリンクを張りたい場合はこのようにする
#7 (参考)

**Comment by maitamin** [comment]
ここに何か書くと何かおきるのか。

**Comment by ta2yak** [comment]
メールが飛びます
